onlyBuiltDependencies:
  - "@prisma/engines"
  - "@tsparticles/engine"
  - bcrypt
  - prisma
  - sharp
  - unrs-resolver

allowBuilds:
  "@prisma/engines": true
  "@tsparticles/engine": true
  bcrypt: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  "@eslint/plugin-kit": ">=0.3.4"