// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// 1. Paksa Prisma membaca file .env.local
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // 🔥 TAMBAHKAN BARIS INI UNTUK MENJALANKAN SEEDER:
    seed: 'ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts',
  },
  datasource: {
    // 2. Gunakan DIRECT_URL untuk membuat tabel di Supabase
    url: process.env["DIRECT_URL"],
  },
});